#!/bin/sh

OUT="tests.inc"

echo "// this file was generated by tests.sh - DO NOT EDIT" > "$OUT"
echo "static const char *AgateTestFiles[] = {" >> "$OUT"

FILES=$(find "tests" -name "*.agate" | grep -v benchmark | sort)

for F in $FILES
do
  if ! grep "nontest" "$F" 2>&1 > /dev/null
  then
    echo "$F" | sed 's/^/  \"/' | sed 's/$/\",/' >> "$OUT"
  fi
done

echo "  NULL" >> "$OUT"
echo "};" >> "$OUT"
